version: "3.3"
services:
  server:
    build: .
    image: yysg/image-labeling-tool:latest
    user: ${CURRENT_UID}
    volumes:
      - "/mnt/vision-nas/image-labeling-tool/uploads:/uploads"
      - "/mnt/vision-nas/image-labeling-tool/db:/db"
    ports:
      - "5000:3000"
